### PR TITLE
Add support for firmware v1.10.0

### PR DESCRIPTION
**Pull request by fabianishere**
This change adds support for the latest firmware release for the UniFi Dream Machine (Pro): version 1.10.0.

See https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-10-0/c4559fe1-52dc-4a6d-8991-d469959d366e
for release details.

### CODE REVIEW

**Comment by TheJulianJES** [comment]
Not sure if you still need it (or already have it), but here's the GPL archive for UDM(P) firmware 1.10.0: https://drive.google.com/file/d/175sVN1rRE9UPByUxZg7MEHK6revK0kfv/view

**Comment by fabianishere** [comment]
@TheJulianJES Thank you, just received it as well!

**Comment by fabianishere** [comment]
Just to give an update, I managed to fix the issue (it was due to still using the v1.9.3 kernel config) and am able to boot into custom kernels again:
```
# uname -a
Linux Router 4.19.152-edge1 #17 SMP Fri Jul 9 17:45:23 UTC 2021 aarch64 GNU/Linux
```

**Comment by fabianishere** [comment]
@TheJulianJES New releases are now available:
- [udm-kernel-tools v1.1.0](https://github.com/fabianishere/udm-kernel-tools/releases/tag/v1.1.0)
- [udm-kernel v4.19.152-edge1](https://github.com/fabianishere/udm-kernel/releases/tag/v4.19.152-edge1)
Let me know if they work for you!

**Comment by TheJulianJES** [comment]
Upgrade went perfectly! Had to copy my ``igmpproxy.conf`` over again and edit the service (to add the ``unifi.service`` dependency) with ``systemctl edit igmpproxy`` but I expected that when doing a firmware upgrade.

Thanks again!

**Pull request merged**
