### PR TITLE
Add support for Linux 4.19 (UDM firmware v1.10.x) 

### PR DESCRIPTION
**Pull request by fabianishere**
This pull request adds support for the newer Linux kernel 4.19 that is shipped in the beta firmware v1.10.x for the UDM/P.

Addresses #6

### CODE REVIEW

**Comment by fabianishere** [comment]
This PR cannot be merged yet unfortunately since kexec-tools seems to have some issues with Linux 4.19 on ARM64.

**Comment by TheJulianJES** [comment]
Is there any bug report we can follow somewhere? (I wasn't able to find one.)

**Comment by fabianishere** [comment]
This is the closest I could find: https://github.com/faust93/android_kernel_nx512j/issues/1

Basically, kexec-tools reads /proc/iomem to determine where to load the kernel. However, the format of /proc/iomem has changed since 4.19 and consequently it cannot find the correct base address.

**Comment by TheJulianJES** [comment]
Sadly I'm not familiar with any of this, so I'm just guessing (and 1.10.x isn't even promoted to "Stable" yet).

You mentioned:
>the format of /proc/iomem has changed since 4.19

Is it possible to just use an older version of kexec-tools where the changes (for newer versions than 4.19) aren't included yet?
If not, is there a version of kexec-tools that works correctly (for 4.19 on ARM64), so the changes can be ported into a newer (custom) version?
Else, would it be possible to raise this issue somewhere else, so it can be fixed directly in kexec-tools?

Although probably unrelated in regards to udm-kernel-tools, can https://github.com/fabianishere/udm-unlock still be used to install a custom kernel from https://github.com/fabianishere/udm-kernel/?

**Comment by fabianishere** [comment]
I think I will approach the issue as follows:
1. We can hardcode the entry point of the kernel directly in `kexec-tools` so correctly parsing `/proc/iomem` is not necessary. This is not a sustainable solution, but we can use it as a workaround in the meantime.
2. The better solution would be to fix the issue in `kexec-tools`, but I haven't had the time to take a good look at this.
3. Finally, `udm-unlock` might also be an option. I am in contact with someone who managed to get the UDM Pro to boot using TFTP. I am interested to see where this might head.

**Comment by k0d** [comment]
> 3. Finally, `udm-unlock` might also be an option. I am in contact with someone who managed to get the UDM Pro to boot using TFTP. I am interested to see where this might head.

Oh, that's me :) I had to put it on hold for a bit...but I'm back looking at it now. I got the kernel to boot a rootfs just fine, which I stored on an external SSD. However I got stuck with getting the network to function. It would show TX packets in the network stats, but no RX.

I was thinking about upgrading the kernel to 4.19, but It looks like you've had issues...so for now I guess I stick with the previous version.

**Comment by fabianishere** [comment]
@k0d Those issues are mostly related to the way udm-kernel-tools works with kexec. If you boot directly via U-Boot, you should have more success.

**Comment by fabianishere** [comment]
I managed to get kexec-tools working again on the latest beta firmware release (v1.10.0-15). See 9485370 for more details.

I am now waiting for the kernel sources for v1.10.0-15 in order to build a compatible kernel. A kernel based on [v1.10.0-8](https://github.com/fabianishere/udm-kernel/tree/flavour/stock-v4.19) seems to be incompatible with the proprietary kernel modules:
> Jul  5 16:34:29 Router user.warn kernel: [    9.370855] ubnt_common: loading out-of-tree module taints kernel.
Jul  5 16:34:29 Router user.warn kernel: [    9.370859] ubnt_common: module license 'Proprietary' taints kernel.
Jul  5 16:34:29 Router user.warn kernel: [    9.373214] ubnt_common: Unknown symbol kmem_cache_alloc_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.373221] ubnt_common: Unknown symbol kmalloc_order_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.373283] ubnt_common: Unknown symbol _mcount (err -2)
Jul  5 16:34:29 Router user.info kernel: [    9.554381] EXT4-fs (sdb4): mounted filesystem with ordered data mode. Opts: errors=panic
Jul  5 16:34:29 Router user.warn kernel: [    9.567760] ubnt_common: Unknown symbol kmem_cache_alloc_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.567766] ubnt_common: Unknown symbol kmalloc_order_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.567829] ubnt_common: Unknown symbol _mcount (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.589857] ubnt_common: Unknown symbol kmem_cache_alloc_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.589864] ubnt_common: Unknown symbol kmalloc_order_trace (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.589924] ubnt_common: Unknown symbol _mcount (err -2)
Jul  5 16:34:29 Router user.warn kernel: [    9.610923] gpiodev: Unknown symbol _mcount (err -2)

**Comment by peacey** [comment]
Hi @fabianishere, did you end up getting the latest kernel sources? I do have the latest one (1.10.0-12) available [here](https://drive.google.com/drive/folders/11CXRjaGsTSTqfs8LdXQ8YoA7tVY_OuHU) since weeks ago. Thanks to @tusc who received it from Ubiquiti.

FYI, in 1.10.0-12, Ubiquiti changed the kernel headers (added a couple variables to some net structures to fix an LLDP bug). So 1.10.0-8 sources were incompatible for compiling modules for 1.10.0-12 and up releases.

**Pull request merged**
